@echo off
:: Define the Base64-encoded PowerShell script
:: I cannot for the life of me output a ps script using plain text here without error and this is easier than escaping as well
set "encoded_script=IyBHZXQgYWxsIGZpbGVzIHJlY3Vyc2l2ZWx5IGluIHRoZSBjdXJyZW50IGRpcmVjdG9yeQokZmlsZXMgPSBHZXQtQ2hpbGRJdGVtIC1SZWN1cnNlIC1GaWxlIC1Gb3JjZQoKIyBUb3RhbCBudW1iZXIgb2YgZmlsZXMKJHRvdGFsID0gJGZpbGVzLkNvdW50CmlmICgkdG90YWwgLWVxIDApIHsKICAgIFdyaXRlLUhvc3QgIk5vIGZpbGVzIGZvdW5kIHRvIHVuYmxvY2suIiAtRm9yZWdyb3VuZENvbG9yIFllbGxvdwogICAgZXhpdAp9CgojIENvbmZpcm1hdGlvbiBwcm9tcHQKJGNvbmZpcm1hdGlvbiA9IFJlYWQtSG9zdCAiUHJvY2VlZCB3aXRoIHVuYmxvY2tpbmcgJHRvdGFsIGZpbGVzPyAoWS9OKSIKaWYgKCRjb25maXJtYXRpb24gLW5lICdZJykgewogICAgV3JpdGUtSG9zdCAiVW5ibG9ja2luZyBjYW5jZWxsZWQuIgogICAgZXhpdAp9CgojIFVuYmxvY2sgZmlsZXMgd2l0aCBwcm9ncmVzcyBiYXIKZm9yICgkaSA9IDA7ICRpIC1sdCAkdG90YWw7ICRpKyspIHsKICAgICRmaWxlID0gJGZpbGVzWyRpXQogICAgVW5ibG9jay1GaWxlIC1QYXRoICRmaWxlLkZ1bGxOYW1lCgogICAgIyBVcGRhdGUgcHJvZ3Jlc3MgYmFyCiAgICBXcml0ZS1Qcm9ncmVzcyAtQWN0aXZpdHkgIlVuYmxvY2tpbmcgZmlsZXMuLi4iIGAKICAgICAgICAgICAgICAgICAgIC1TdGF0dXMgIlByb2Nlc3NpbmcgJCgkZmlsZS5OYW1lKSIgYAogICAgICAgICAgICAgICAgICAgLVBlcmNlbnRDb21wbGV0ZSAoKCRpICsgMSkgLyAkdG90YWwgKiAxMDApCn0KCldyaXRlLUhvc3QgIlVuYmxvY2tpbmcgY29tcGxldGVkLiIgLUZvcmVncm91bmRDb2xvciBHcmVlbgo="

:: Create the PowerShell script from Base64 string
echo %encoded_script% | powershell -Command "$encodedScript = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('%encoded_script%')); $encodedScript | Set-Content -Path 'unblock_ps.ps1'"

:: Execute the decoded PowerShell script
powershell -ExecutionPolicy Bypass -File unblock_ps.ps1

:: Optionally delete the decoded script after execution
del unblock_ps.ps1

pause
